# Generated by Django 5.2.7 on 2025-10-20 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_cart_cartitem'),
        ('enrollments', '0002_enrollment_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('course',)},
        ),
    ]
