# Generated by Django 5.2.7 on 2025-10-25 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0004_alter_enrollment_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='cart',
        ),
    ]
