# Generated by Django 5.2.7 on 2025-10-20 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='payment_method',
        ),
    ]
