# Generated by Django 5.2.7 on 2025-10-20 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_cart_cartitem'),
        ('payment', '0002_remove_paymenttransaction_payment_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='course',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.cart'),
        ),
    ]
