# Generated by Django 5.2.7 on 2025-10-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='status',
            field=models.CharField(choices=[('in_cart', 'In Cart'), ('sold', 'Sold')], default='in_cart', max_length=15),
        ),
    ]
